<a href="https://colab.research.google.com/github/nitishainita/numpy_practice/blob/main/numpy_function.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### NumPy functions

In [1]:
import numpy as np

### arange()

In [2]:
ar_1d=np.arange(1,13)
print(ar_1d)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [3]:
# for even number aaray usnig arange function
even_ar=np.arange(0,13,2)
print(even_ar)

[ 0  2  4  6  8 10 12]


### linsapce()

In [4]:
space_ar=np.linspace(1,5,4)
print(space_ar)

[1.         2.33333333 3.66666667 5.        ]


### reshape()

In [5]:
ar_2d=ar_1d.reshape(2,6)
print(ar_2d)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [6]:
ar_3d=ar_1d.reshape(2,3,2)
print(ar_3d)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [7]:
ar=np.arange(1,17).reshape(4,4)
print(ar)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


### for n-d to 1d array

#### reval()

In [8]:
ar.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

### flatten()

In [9]:
ar.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [10]:
ar

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [11]:
ar.transpose()

array([[ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15],
       [ 4,  8, 12, 16]])