<a href="https://colab.research.google.com/github/nitishainita/numpy_practice/blob/main/numpy_prac1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
arr_1d=np.array([1,2,3,4])
print(arr_1d)

[1 2 3 4]


In [ ]:
type(arr_1d)

numpy.ndarray

In [ ]:
arr_1d.ndim

1

In [ ]:
arr_2d=np.array([[1,2,3,4],[5,6,7,8]])
print(arr_2d)

[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
arr_2d.size

8

In [ ]:
arr_2d.shape

(2, 4)