<a href="https://colab.research.google.com/github/nitishainita/numpy_practice/blob/main/Random_sampling_with_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import random

In [2]:
np.random.random(1)

array([0.36134321])

### for 2d random array values between 0 and 1

In [3]:
np.random.random((3,3))

array([[0.38230005, 0.94929526, 0.84182878],
       [0.00234923, 0.13673182, 0.70447448],
       [0.74624019, 0.07949023, 0.91895605]])

### for given rannge

In [4]:
np.random.randint(1,4)

2

In [5]:
np.random.randint(1,4,(4,4))

array([[3, 1, 1, 1],
       [1, 1, 1, 1],
       [3, 1, 1, 1],
       [2, 1, 2, 2]])

In [6]:
np.random.randint(1,4,(2,4,4))

array([[[2, 1, 3, 3],
        [1, 1, 1, 1],
        [2, 3, 1, 1],
        [2, 1, 1, 1]],

       [[2, 2, 3, 3],
        [2, 2, 1, 3],
        [1, 1, 3, 2],
        [1, 2, 2, 1]]])

## Seed value is used for remembering the random numbers for future use and value must be in between 0 to 2**32-1

In [7]:
np.random.seed(10)
np.random.randint(1,4,(2,4,4))

array([[[2, 2, 1, 1],
        [2, 1, 2, 2],
        [1, 2, 2, 3],
        [1, 2, 1, 3]],

       [[1, 3, 1, 1],
        [1, 3, 1, 3],
        [3, 2, 1, 1],
        [3, 2, 3, 2]]])

In [8]:
np.random.seed(10)
np.random.randint(1,4,(2,4,4))

array([[[2, 2, 1, 1],
        [2, 1, 2, 2],
        [1, 2, 2, 3],
        [1, 2, 1, 3]],

       [[1, 3, 1, 1],
        [1, 3, 1, 3],
        [3, 2, 1, 1],
        [3, 2, 3, 2]]])

### for creating nd array using rand function

In [9]:
np.random.rand(3)#going to get values between 0 to 1

array([0.13145815, 0.41366737, 0.77872881])

In [10]:
np.random.rand(3,3)

array([[0.58390137, 0.18263144, 0.82608225],
       [0.10540183, 0.28357668, 0.06556327],
       [0.05644419, 0.76545582, 0.01178803]])

In [11]:
np.random.randn(3,3)#going to get negative and positive values as standered normal distribution

array([[-1.58494101,  1.05535316, -1.92657911],
       [ 0.69858388, -0.74620143, -0.15662666],
       [-0.19363594,  1.13912535,  0.36221796]])

In [12]:
x=[1,2,3,4,5,6]
np.random.choice(x)

1

In [13]:
for i in range(10):
    print(np.random.choice(x))

1
5
6
5
1
1
3
5
3
1


In [14]:
np.random.permutation(x)

array([3, 5, 2, 4, 1, 6])

In [15]:
np.random.permutation(x)

array([2, 4, 1, 5, 3, 6])